application: misty-cms
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /static
  static_dir: static

- url: /api/.*
  script: main.app

- url: /a/test
  script: main.app
  login: admin

- url: /a/.*
  script: main.app
  login: required

- url: .*
  script: main.app
